In [2]:
pip install tensorflow-hub

In [3]:
import tensorflow as tf
import tensorflow_hub as hub

In [5]:
pip install tensorflow-text

     ---------------------------------------- 5.0/5.0 MB 7.8 MB/s eta 0:00:00
     ---------------------------------------- 24.4/24.4 MB 5.9 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 5.9 MB/s eta 0:00:00
     -------------------------------------- 896.6/896.6 kB 5.7 MB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
Note: you may need to restart the kernel to use updated packages.


In [6]:
import tensorflow_text as text

In [7]:
bert_preprocess=hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder=hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

In [8]:
bert_preprocess_model=hub.KerasLayer(bert_preprocess)

In [9]:
text_test=["The cat chased its tail in circles, circles.","I love python programming "]
text_preprocess=bert_preprocess_model(text_test)


In [46]:
text_preprocess['input_mask']   #12 1's means cls then 9 words and then sep for 1st sentence means token of the sentence

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [10]:
bert_model=hub.KerasLayer(bert_encoder)
bert_results=bert_model(text_preprocess)

In [11]:
bert_results['pooled_output']  # sentence Embeddings

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.93874604, -0.4661817 , -0.9566651 , ..., -0.8107919 ,
        -0.75763863,  0.9417425 ],
       [-0.917123  , -0.47935176, -0.78656995, ..., -0.61751735,
        -0.71026856,  0.92184293]], dtype=float32)>

In [41]:
# Word Embeddings

In [62]:
bert_results['sequence_output']  

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-0.19137892,  0.18068177, -0.0767023 , ..., -0.31555057,
          0.5168401 ,  0.65179956],
        [-0.32744744,  0.2293959 , -0.40656632, ..., -0.18453339,
          1.4228282 , -0.10496231],
        [-0.29930723, -0.03205732,  0.08453795, ..., -0.26316696,
          0.7589273 ,  0.8098604 ],
        ...,
        [-0.09657381, -0.11103138,  0.24296999, ...,  0.45229593,
          0.287086  , -0.27062276],
        [-0.14344566,  0.22066672,  0.2835129 , ...,  0.130868  ,
          0.1386325 ,  0.1856568 ],
        [-0.15755695,  0.14830534,  0.3560956 , ...,  0.1420857 ,
          0.11493847,  0.1238061 ]],

       [[-0.07900575,  0.36335123, -0.2110158 , ..., -0.17183745,
          0.16299747,  0.67242604],
        [ 0.27883554,  0.43716234, -0.3576479 , ..., -0.04463585,
          0.38315207,  0.5887979 ],
        [ 1.2037677 ,  1.0727022 ,  0.4840873 , ...,  0.24921006,
          0.40730906,  0.40481764],
        ...,

In [ ]:
#This is a matrix or tensor with shape (2, 128, 768), where 2 is the number of sentences, 
#128 is the padded length of each sentence and 768 is the size of the embedding vector for each word or token in the sentence.
#Each element of the sequence_output is a vector representing the contextualized embedding for a token in an input sentence. 
#The padding is added to all sequences to make them uniform length and allow for efficient parallel processing. 
#The padded positions are filled with zeros which do not contribute to the model’s output.

In [14]:
pip install transformers


     ---------------------------------------- 7.2/7.2 MB 5.1 MB/s eta 0:00:00
     -------------------------------------- 268.8/268.8 kB 3.3 MB/s eta 0:00:00
     -------------------------------------- 269.0/269.0 kB 4.1 MB/s eta 0:00:00
     -------------------------------------- 270.2/270.2 kB 3.3 MB/s eta 0:00:00
     ---------------------------------------- 78.3/78.3 kB 1.4 MB/s eta 0:00:00
     ---------------------------------------- 3.5/3.5 MB 10.1 MB/s eta 0:00:00
     -------------------------------------- 153.2/153.2 kB 2.3 MB/s eta 0:00:00
     -------------------------------------- 143.0/143.0 kB 2.1 MB/s eta 0:00:00


In [28]:
from transformers import BertTokenizer, TFBertModel
import tensorflow as tf

# Load pre-trained BERT model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained('bert-base-uncased')

# Input sentence
sentence = "This is an example sentence for obtaining word embeddings using BERT."

# Tokenize input sentence
tokens = tokenizer.encode(sentence, add_special_tokens=True)

# Convert tokens to a TensorFlow tensor
input_ids = tf.constant([tokens])

# Get word embeddings
outputs = model(input_ids)

# Extract word embeddings from BERT model outputs
word_embeddings = outputs.last_hidden_state

print("Word embeddings shape:", word_embeddings.shape)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

Word embeddings shape: (1, 17, 768)


In [29]:
word_embeddings

<tf.Tensor: shape=(1, 17, 768), dtype=float32, numpy=
array([[[-0.17084476, -0.41360137, -0.43313703, ..., -0.5292205 ,
          0.04097911,  0.8489252 ],
        [-0.8059007 , -0.41379577, -0.63023555, ..., -0.18820429,
          0.78443885,  0.33575237],
        [-0.60413   , -0.49594197, -0.24926035, ...,  0.01484546,
          0.43269378,  0.83540964],
        ...,
        [ 0.9739794 , -0.10077645,  0.35819316, ..., -0.4317742 ,
         -0.57785165,  0.1323593 ],
        [ 0.66213924,  0.0910468 , -0.80978787, ...,  0.23369831,
         -0.6674618 , -0.31742436],
        [ 0.54593205,  0.09528682, -0.5490752 , ...,  0.46521395,
         -0.9474096 , -0.28504142]]], dtype=float32)>

In [63]:

# Input sentence
sentence = "This is an example sentence for obtaining word embeddings using BERT."

# Tokenize input sentence
tokens = tokenizer.encode(sentence, add_special_tokens=True)

# Convert tokens to a TensorFlow tensor
input_ids = tf.constant([tokens])

# Get word embeddings
outputs = model(input_ids)

# Extract word embeddings from BERT model outputs
word_embeddings = outputs.last_hidden_state

# Remove padding tokens from word embeddings
padding_mask = tf.cast(input_ids != tokenizer.pad_token_id, word_embeddings.dtype)
word_embeddings = word_embeddings * tf.expand_dims(padding_mask, axis=-1)

# Convert token IDs to words
words = tokenizer.convert_ids_to_tokens(tokens)

# Convert word embeddings to a DataFrame
df = pd.DataFrame(word_embeddings.numpy().squeeze(), columns=[f"vector_{i}" for i in range(word_embeddings.shape[-1])])
df['word'] = words

# Drop rows corresponding to padding tokens
df = df[df['word'] != '[PAD]']

# Reset index
df.reset_index(drop=True, inplace=True)

print(df)

    vector_0  vector_1  vector_2  vector_3  vector_4  vector_5  vector_6  \
0  -0.170845 -0.413601 -0.433137 -0.285086 -0.411366 -0.182735  0.213057   
1  -0.805901 -0.413796 -0.630236 -0.582564  0.486166  0.062290  0.556166   
2  -0.604130 -0.495942 -0.249260 -0.283324 -0.058351  0.018988  0.978645   
3  -0.476405 -0.466202 -0.499740 -0.415646 -0.115020 -0.282501  0.776292   
4  -0.595442 -0.439979 -0.802423 -0.903680  0.127847  0.098732  0.272392   
5   0.070090 -0.114060 -0.071044 -0.697330  0.495325  0.267586  0.591683   
6  -0.063174  0.258550 -0.034728 -0.034108  0.307785  0.084003  0.372943   
7  -0.421442 -0.258147 -0.159953 -0.417999  0.076198  0.034850  0.290036   
8  -0.139541 -0.017897  0.266034 -0.419038 -0.259675  0.445429  0.266482   
9   0.325438  0.001303  0.084627 -0.369053  0.282410  0.415590 -0.163227   
10  0.399742  0.025163  0.043084 -0.362132  0.124477  0.226699  0.121282   
11  0.107765  0.092439  0.190629 -0.312216  0.375558  0.240410 -0.109197   
12 -0.101577

In [58]:
sentence = ["This is an example sentence for obtaining word embeddings using BERT."]

In [60]:
text_preprocess=bert_preprocess_model(sentence)
text_preprocess['input_mask']   # here also 17's one indicate divide into 17 tokens and then padded zeroes to make a shape of 128

<tf.Tensor: shape=(1, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [ ]:
#padding is used to ensure that all sequences within a batch have the same length.
#Text=["This is an example sentence.", "Another sentence for illustration.", "A third sentence."]

#Sentence1= ["[CLS]", "This", "is", "an", "example", "sentence", ".", "[SEP]"]
#Sentence2= ["[CLS]", "Another", "sentence", "for", "illustration", ".", "[SEP]"]
#Sentence3= ["[CLS]", "A", "third", "sentence", ".", "[SEP]"]

#Sentence 1: 8 tokens
#Sentence 2: 7 tokens
#Sentence 3: 6 tokens

#The longest sequence has 8 tokens. Therefore, we pad the shorter sequences with [PAD] tokens to match this length
#After padding sentences looks like:-
#Sentence1=  ["[CLS]", "This", "is", "an", "example", "sentence", ".", "[SEP]"]
#Sentence2=  ["[CLS]", "Another", "sentence", "for", "illustration", ".", "[SEP]", "[PAD]"]
#Sentence3=  ["[CLS]", "A", "third", "sentence", ".", "[SEP]", "[PAD]", "[PAD]"]
# in general word scenario it is padded with generally 128 for each sentences

In [40]:
# Two sentences with different word limits
sentences = [
    "This is the first sentence with the fewer words.",
    "This is the second sentence with more words and a higher word limit."
]

# Tokenize sentences and convert to input IDs
input_ids = [tokenizer.encode(sentence, add_special_tokens=True) for sentence in sentences]

# Get maximum length among the input sequences
max_length = max(len(ids) for ids in input_ids)

# Pad input sequences to the maximum length
input_ids_padded = [ids + [tokenizer.pad_token_id] * (max_length - len(ids)) for ids in input_ids]

# Convert to TensorFlow tensors
input_ids_tensor = tf.constant(input_ids_padded)

# Get word embeddings
outputs = model(input_ids_tensor)

# Extract word embeddings from BERT model outputs for both sentences
word_embeddings = outputs.last_hidden_state.numpy()

# Print words along with their embedding vectors for both sentences
for i, embeddings in enumerate(word_embeddings):
    words = tokenizer.convert_ids_to_tokens(input_ids_padded[i])
    print(f"Sentence {i + 1}:")
    for word, embedding in zip(words, embeddings):
        print(f"Word: {word}, Embedding: {embedding}")
    print()

Sentence 1:
Word: [CLS], Embedding: [-5.39150536e-01 -3.52997184e-01  7.57008046e-03 -1.63571209e-01
 -6.45546079e-01 -3.99650633e-01  4.32762206e-01  4.45196360e-01
 -1.03649281e-01 -5.66634893e-01 -1.26087844e-01 -3.23506176e-01
  2.31475458e-02  2.87834883e-01  4.61393267e-01 -1.02397859e-01
 -1.38815373e-01  7.67158329e-01  2.91856050e-01 -3.78504485e-01
 -8.26686621e-02  6.11961260e-02  6.69852853e-01  1.73110798e-01
  5.35679013e-02 -2.17378914e-01  4.47127298e-02 -3.13964754e-01
 -6.18161112e-02 -6.31526887e-01 -2.10146561e-01  5.15864849e-01
 -3.92103881e-01 -7.84497857e-02  4.45102870e-01 -3.14338297e-01
 -1.58731997e-01  1.60229892e-01  2.68078834e-01 -7.10759219e-03
  2.72029340e-02 -2.83725560e-01  2.44289055e-01 -7.22070970e-03
 -5.04453555e-02 -7.73943365e-01 -3.63093209e+00 -2.11521149e-01
 -6.62141144e-01 -3.51141512e-01 -4.64802146e-01 -1.84940532e-01
  6.05395615e-01  4.00460243e-01  6.02072999e-02  1.03452945e+00
 -4.95640576e-01 -5.04031964e-03  6.17176712e-01  1.38

In [64]:
# sentence1: word embeddings for [CLS], Each word, [Sep], then 4 pads beacause sentence 1 has less words so to make parallel with the 2nd senetnce
# sentence2: word Embeddings for {CLS}, Each word ,[SEP]

In [65]:
# End